name = "argham"
version = "0.1.0"
license = "MIT"
author = "arkeasz"
description = "Symbolic calculator and recursive descent parser written in Fortran"
homepage = "https://github.com/arkeasz/argham"

[library]
source-dir = "src"          

[[executable]]
name = "argham"
source-dir = "app"
main = "main.f90"

[build]
auto-executables = false
auto-tests = false
module-naming = true